//------------------------------------------------------------------------
// Copyright(c) 2022 quero.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"NanoSynth.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"NanoSynth VST3 (64Bit)"
#else
#define stringFileDescription	"NanoSynth VST3"
#endif
#define stringCompanyName		"quero\0"
#define stringLegalCopyright	"Copyright(c) 2022 quero."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
